Azure/azure-sdk-for-ruby

README.md
Rakefile
lib/azure/service_bus/relay.rb
lib/azure/service_bus/serialization.rb
lib/azure/service_bus/service_bus_service.rb
test/fixtures/sb_default_create_relay_response.xml
test/integration/service_bus/relay_test.rb
test/support/name_generator.rb

Added support to create / delete relay endpoints. Added tests to cover these changes as well.

Adding support for Service Bus Relay

---

lib/azure/blob/auth/shared_access_signature.rb
lib/azure/blob/blob_service.rb
test/unit/blob/auth/shared_access_signature_test.rb

I still intend to add convenience methods for consistency on BlobService itself, but this is useable as is.

Blob service shared access signatures

---

README.md
lib/azure/virtual_machine_management/virtual_machine_management_service.rb

Allow access to the new VM sizes D*, DS* and G*
https://msdn.microsoft.com/en-us/library/azure/dn197896.aspx

Allow access for the new VM sizes

---

.env_sample
.gitignore
README.md
Rakefile
azure.gemspec
lib/azure.rb
lib/azure/base_management/base_management_service.rb
lib/azure/base_management/management_http_request.rb
lib/azure/cloud_service_management/cloud_service_management_service.rb
lib/azure/core.rb
lib/azure/core/configuration.rb
lib/azure/core/http/http_request.rb
lib/azure/virtual_machine_management/virtual_machine_management_service.rb
test/integration/affinity_group/Create_Affinity_test.rb
test/integration/affinity_group/Update_Affinity_test.rb
test/integration/cloud_service/Cloud_Create_test.rb
test/integration/cloud_service/Cloud_Delete_test.rb
test/integration/storage_management/storage_management_test.rb
test/integration/test_helper.rb
test/integration/vm/VM_Create_test.rb
test/test_helper.rb
test/unit/core/http/http_request_test.rb

- Add support for ca_certs to be specified in the Azure configuration
- Turn on VERIFY_PEER to mitigate MITM 
- Fix up the namespace refactor as it missed some usages

Add ca_certs support and clean up the namespace refactor

---

.travis.yml
README.md
azure.gemspec
test/integration/affinity_group/Create_Affinity_test.rb
test/integration/affinity_group/Delete_Affinity_test.rb
test/integration/affinity_group/Update_Affinity_test.rb
test/integration/service_bus/queues_test.rb
test/integration/service_bus/relay_test.rb
test/integration/storage_management/storage_management_test.rb
test/integration/vnet/Virtual_Network_list_test.rb
test/test_helper.rb
test/unit/affinity_group/affinity_group_test.rb
test/unit/affinity_group/serialization_test.rb
test/unit/base_management/location_test.rb
test/unit/blob/blob_service_test.rb
test/unit/cloud_service_management/cloud_service_management_service_test.rb
test/unit/core/auth/shared_key_lite_test.rb
test/unit/core/auth/shared_key_test.rb
test/unit/core/http/http_error_test.rb
test/unit/database/serialization_test.rb
test/unit/database/sql_database_server_service_test.rb
test/unit/service/storage_service_test.rb
test/unit/storage_management/storage_management_service_test.rb
test/unit/virtual_machine_image_management/virtual_machine_image_management_service_test.rb
test/unit/virtual_machine_management/virtual_machine_management_service_test.rb

- add rb testing in travis for 2.1 and 2.2
- update the readme to reflect the ruby versions
- update to minitest ~> 5
- change location, name and method to geo_location, *_name and verb to satisfy minitest

travis testing on rb 2.1 & 2.2, update the readme and minitest 5

---

lib/azure/service_bus/relay.rb
test/integration/affinity_group/Create_Affinity_test.rb
test/integration/service_bus/relay_test.rb
test/integration/test_helper.rb

- fix a couple missed location and service bus names
- fix a minitest change that was missed in the minitest upgrade
- make service bus options optional

fix up some of the integration tests that broke

---

lib/azure/base_management/base_management_service.rb
lib/azure/base_management/location.rb
lib/azure/base_management/serialization.rb
lib/azure/virtual_machine_management/virtual_machine_management_service.rb
test/fixtures/list_locations.xml
test/integration/location/RoleSize_List_test.rb
test/unit/base_management/role_size_test.rb
test/unit/virtual_machine_management/virtual_machine_management_service_test.rb

There is a requirement to list rolesizes for a subscription.

Added support to list role sizes for a subscription

---

azure.gemspec

Increment mime-types dependency to ~2.0

---

README.md

Very minor fix changing Java > Ruby

s/Java/Ruby in README.md

---

.gitignore
service_management/azure/lib/azure/sql_database_management/sql_database_management_service.rb

Use 'net/http get' to replace curl to fix a testing failure.

Fixed a curl bug for windows

---

service_management/azure/lib/azure/http_client.rb

Related to this issue https://github.com/Azure/azure-sdk-for-ruby/issues/294

No agent reuse to fix an invalid request url bug.

---

resource_management/azure_mgmt_compute/azure_mgmt_compute.gemspec
resource_management/azure_mgmt_compute/lib/azure_mgmt_compute/version.rb
resource_management/azure_mgmt_network/azure_mgmt_network.gemspec
resource_management/azure_mgmt_network/lib/azure_mgmt_network/version.rb
resource_management/azure_mgmt_resources/azure_mgmt_resources.gemspec
resource_management/azure_mgmt_resources/lib/azure_mgmt_resources/version.rb
resource_management/azure_mgmt_storage/azure_mgmt_storage.gemspec
resource_management/azure_mgmt_storage/lib/azure_mgmt_storage/version.rb

https://github.com/Azure/azure-sdk-for-ruby/issues/321

increment gem versions and constrain msrest dependency

---

README.md

Adding a brief note to consider when working against Azure Government endpoints.

Adding note for Azure Government to readme

---

service_management/azure/lib/azure/blob/auth/shared_access_signature.rb
service_management/azure/test/unit/blob/auth/shared_access_signature_test.rb

Converting start and expiry options to UTC in ISO8601 format per spec

---

service_management/azure/lib/azure/virtual_machine_management/serialization.rb
service_management/azure/test/fixtures/virtual_machine.xml
service_management/azure/test/unit/virtual_machine_management/serialization_test.rb

Adding serialization for udp endpoints and corresponding tests.

---

.travis.yml

@veronicagg @devigned 
Could you please review this change to release Azure ASM gem from travis?

Deploy Azure ASM gem from travisCI

---

README.md
service_management/README.md

Updating readme file

---

service_management/azure/lib/azure/client_services.rb
service_management/azure/test/unit/config/client_services_test.rb

Updating how default_client sets options 

---

.travis.yml

Branch master is the default one so no need to specif explicitly.

Re-add api-key to travis file

---

.travis.yml
resource_management/Gemfile
resource_management/Rakefile
resource_management/azure_mgmt_storage/spec/spec_helper.rb
resource_management/azure_mgmt_storage/spec/storage_accounts_spec.rb
resource_management/azure_mgmt_storage/spec/usage_operations_spec.rb
resource_management/azure_mgmt_storage/spec/vcr_cassettes/create_storage_account.yml
resource_management/azure_mgmt_storage/spec/vcr_cassettes/list_storage_accounts.yml
resource_management/azure_mgmt_storage/spec/vcr_cassettes/list_storage_accounts_by_resource_group.yml
resource_management/azure_mgmt_storage/spec/vcr_cassettes/list_usage_operations.yml
resource_management/azure_mgmt_storage/spec/vcr_cassettes/should_delete_storage.yml
resource_management/azure_mgmt_storage/spec/vcr_cassettes/should_get_storage_account_keys.yml
resource_management/azure_mgmt_storage/spec/vcr_cassettes/should_get_storage_account_properties.yml
resource_management/azure_mgmt_storage/spec/vcr_cassettes/should_regenerate_storage_account_keys.yml
resource_management/azure_mgmt_storage/spec/vcr_cassettes/should_send_true_if_name_is_available.yml
resource_management/azure_mgmt_storage/spec/vcr_cassettes/should_update_storage.yml
resource_management/vcr_helper.rb

Adding support for VCR recording in ARM azure_mgmt_storage service
This changes is part of the feature #291

VCR recording for azure_mgmt_storage service

---

azure.gemspec
lib/azure/table/batch.rb

Addressing Issue #391 as per the sample PR provided at PR #390

Replace uuid gem with SecureRandom

---

azure_mgmt_iot_hub/lib/generated/azure_mgmt_iot_hub/models/operation_inputs.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/470

Automatic PR from RestAPI-PR470

---

azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/usage_management_client.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/486

Automatic PR from RestAPI-PR486

---

azure_mgmt_network/lib/generated/azure_mgmt_network/models/virtual_network_gateway_sku.rb
azure_mgmt_network/lib/generated/azure_mgmt_network/models/virtual_network_gateway_sku_name.rb
azure_mgmt_network/lib/generated/azure_mgmt_network/models/virtual_network_gateway_sku_tier.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/500

Automatic PR from RestAPI-PR500

---

azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/classic_administrator_list_result.rb
azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/permission_get_result.rb
azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/provider_operations_metadata_list_result.rb
azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/role_definition_list_result.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/542

Automatic PR from RestAPI-PR542

---

azure_mgmt_media_services/lib/generated/azure_mgmt_media_services.rb
azure_mgmt_media_services/lib/generated/azure_mgmt_media_services/media_service_operations.rb
azure_mgmt_media_services/lib/generated/azure_mgmt_media_services/models/check_name_availability_input.rb
azure_mgmt_media_services/lib/generated/azure_mgmt_media_services/models/check_name_availability_output.rb
azure_mgmt_media_services/lib/generated/azure_mgmt_media_services/models/resource_type.rb
azure_mgmt_media_services/lib/generated/azure_mgmt_media_services/version.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/540

Automatic PR from RestAPI-PR540

---

azure_sdk/azure_sdk.gemspec

Removed dependency from azure_mgmt_service_bus

Removed dependency from azure_mgmt_service_bus

---

.travis.yml

As we had issues couple of time at the moment of releasing sdks they stops building due to various reasons, I am just including gem building process in the travis to avoid these surprises.

Build gems for verification in travis

---

azure_mgmt_graph/lib/generated/azure_mgmt_graph/models/key_credentials_update_parameters.rb
azure_mgmt_graph/lib/generated/azure_mgmt_graph/models/password_credentials_update_parameters.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/565

Automatic PR from RestAPI-PR565

---

azure_mgmt_graph/lib/generated/azure_mgmt_graph/applications.rb
azure_mgmt_graph/lib/generated/azure_mgmt_graph/graph_rbac_management_client.rb
azure_mgmt_graph/lib/generated/azure_mgmt_graph/models/application_list_result.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/578

Automatic PR from RestAPI-PR578

---

Rakefile
swagger_to_sdk_config.json

Due to recent commits https://github.com/Azure/azure-rest-api-specs/commit/f22aaad1ec4218856eb64515ec5215af202401ee
#511

Updating path for azure analysis service's swagger file

---

management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/availability_set.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/list_usages_result.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/611

Automatic PR from RestAPI-PR611

---

management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/event_hub_properties.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/event_hub_resource.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/613

Automatic PR from RestAPI-PR613

---

swagger_to_sdk_config.json

Reverts Azure/azure-sdk-for-ruby#508

Revert "Updating to fixed version of autorest temporarily"

---

management/azure_mgmt_compute/lib/generated/azure_mgmt_compute.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/compute_management_client.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/container_services.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/availability_set.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_agent_pool_profile.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_diagnostics_profile.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_linux_profile.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_list_result.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_master_profile.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_orchestrator_profile.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_ssh_configuration.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_vmdiagnostics.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_windows_profile.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/list_usages_result.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/634

Automatic PR from RestAPI-PR634

---

runtime/ms_rest/ms_rest.gemspec
runtime/ms_rest_azure/ms_rest_azure.gemspec

Related to Azure/azure-sdk-for-ruby#490
@vishrutshah @veronicagg Can you review this PR?

Removing Json dependency from the runtime

---

azure.gemspec

1. https://github.com/Azure/azure-sdk-for-ruby/issues/482
2. https://github.com/Azure/azure-sdk-for-ruby/issues/490 
@vishrutshah @veronicagg Can you review this PR?

Remove Json dependency and modify mime-types dependency

---

management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/deep_created_origin.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/geo_filter.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/origin.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/origin_update_parameters.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/origins.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/632

Automatic PR from RestAPI-PR632

---

management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_agent_pool_profile.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_linux_profile.rb
management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/container_service_windows_profile.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/642

Automatic PR from RestAPI-PR642

---

Rakefile
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/backup_engines.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/backup_operation_results.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/backup_operation_statuses.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/backups.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/export_jobs_operation_results.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/item_level_recovery_connections.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/job_cancellations.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/job_details.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/job_operation_results.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/jobs.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protectable_items.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protected_item_operation_results.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protected_item_operation_statuses.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protected_items.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protection_container_operation_results.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protection_container_refresh_operation_results.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protection_containers.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protection_policies.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protection_policy_operation_results.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/protection_policy_operation_statuses.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/recovery_points.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/recovery_services_backup_client.rb
management/azure_mgmt_recovery_services_backup/lib/generated/azure_mgmt_recovery_services_backup/restores.rb
swagger_to_sdk_config.json

Using composite swagger spec from https://github.com/Azure/azure-rest-api-specs/tree/master/arm-recoveryservicesbackup

Use composite swagger for Azure Recovery backup service

---

management/azure_mgmt_media_services/lib/generated/azure_mgmt_media_services/models/media_service.rb
management/azure_mgmt_media_services/lib/generated/azure_mgmt_media_services/models/tracked_resource.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/641

Automatic PR from RestAPI-PR641

---

management/azure_mgmt_dns/lib/generated/azure_mgmt_dns.rb
management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/models/http_status_code.rb
management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/models/zone_delete_result.rb
management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/record_sets.rb
management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/zones.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/615

Automatic PR from RestAPI-PR615

---

management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/models/record_set.rb
management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/models/record_set_list_result.rb
management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/models/record_set_update_parameters.rb
management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/models/zone.rb
management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/models/zone_delete_result.rb
management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/record_sets.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/650

Automatic PR from RestAPI-PR650

---

management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/check_name_availability_result.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/custom_domain.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/encryption.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/encryption_service.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/encryption_services.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/endpoints.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/sku.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/storage_account.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/storage_account_create_parameters.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/storage_account_key.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/storage_account_list_keys_result.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/storage_account_list_result.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/storage_account_update_parameters.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/usage_list_result.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/models/usage_name.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/storage_accounts.rb
management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/storage_management_client.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/655

Automatic PR from RestAPI-PR655

---

azure.gemspec
test/unit/virtual_machine_management/virtual_machine_management_service_test.rb

Refer https://github.com/freerange/mocha/issues/276#issuecomment-256659551 for details. 
@vishrutshah @veronicagg @salameer Please review and approve this PR.

Fixing the mocha dependency

---

runtime/ms_rest/CHANGELOG.md
runtime/ms_rest/README.md
runtime/ms_rest/lib/ms_rest/version.rb
runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/README.md
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb
runtime/ms_rest_azure/ms_rest_azure.gemspec

This is part 3 of the feature work https://github.com/Azure/azure-sdk-for-ruby/issues/517

Preparing for release of 0.6.1 of ms_rest & ms_rest_azure

---

ChangeLog.md
lib/azure/version.rb

https://github.com/Azure/azure-sdk-for-ruby/issues/558

Preparing for release of azure gem v0.7.7

---

management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/day_of_week.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/export_rdbparameters.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/import_rdbparameters.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_access_keys.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_create_parameters.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_list_result.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_patch_schedule.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_reboot_parameters.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_regenerate_key_parameters.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_resource.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_update_parameters.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/schedule_entry.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/sku.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/patch_schedules.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/redis.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/redis_management_client.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/708

Automatic PR from RestAPI-PR708

---

management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/authorization_management_client.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/classic_administrators.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/classic_administrator.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/classic_administrator_list_result.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/classic_administrator_properties.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/permission.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/permission_get_result.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/provider_operation.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/provider_operations_metadata.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/provider_operations_metadata_list_result.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/resource_type.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/role_assignment.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/role_assignment_create_parameters.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/role_assignment_list_result.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/role_assignment_properties.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/role_assignment_properties_with_scope.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/role_definition.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/role_definition_list_result.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/models/role_definition_properties.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/permissions.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/provider_operations_metadata_operations.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/role_assignments.rb
management/azure_mgmt_authorization/lib/generated/azure_mgmt_authorization/role_definitions.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/704

Automatic PR from RestAPI-PR704

---

management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/deployment_operations.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/deployments.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/alias_path_type.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/debug_setting.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/deployment_list_result.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/deployment_operation.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/deployment_operations_list_result.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/deployment_properties.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/deployment_properties_extended.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/export_template_request.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/generic_resource.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/identity.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/parameters_link.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/provider.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/provider_list_result.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/provider_resource_type.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/resource_group.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/resource_group_list_result.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/resource_list_result.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/resource_management_error_with_details.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/resources_move_info.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/sku.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/tag_details.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/tags_list_result.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/template_link.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/providers.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/resource_groups.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/resource_management_client.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/resources.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/tags.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/690

Automatic PR from RestAPI-PR690

---

management/azure_mgmt_powerbi_embedded/lib/generated/azure_mgmt_powerbi_embedded/models/check_name_response.rb
management/azure_mgmt_powerbi_embedded/lib/generated/azure_mgmt_powerbi_embedded/models/display.rb
management/azure_mgmt_powerbi_embedded/lib/generated/azure_mgmt_powerbi_embedded/models/migrate_workspace_collection_request.rb
management/azure_mgmt_powerbi_embedded/lib/generated/azure_mgmt_powerbi_embedded/models/operation.rb
management/azure_mgmt_powerbi_embedded/lib/generated/azure_mgmt_powerbi_embedded/power_biembedded_management_client.rb
management/azure_mgmt_powerbi_embedded/lib/generated/azure_mgmt_powerbi_embedded/workspace_collections.rb
management/azure_mgmt_powerbi_embedded/lib/generated/azure_mgmt_powerbi_embedded/workspaces.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/688

Automatic PR from RestAPI-PR688

---

management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/message_count_details.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/namespace_create_or_update_parameters.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/namespace_list_result.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/namespace_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/queue_create_or_update_parameters.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/queue_list_result.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/queue_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/regenerate_keys_parameters.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/resource_list_keys.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/shared_access_authorization_rule_create_or_update_parameters.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/shared_access_authorization_rule_list_result.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/shared_access_authorization_rule_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/sku.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/subscription_create_or_update_parameters.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/subscription_list_result.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/subscription_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/topic_create_or_update_parameters.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/topic_list_result.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/topic_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/namespaces.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/queues.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/service_bus_management_client.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/subscriptions.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/topics.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/678

Automatic PR from RestAPI-PR678

---

management/azure_mgmt_features/lib/generated/azure_mgmt_features/feature_client.rb
management/azure_mgmt_features/lib/generated/azure_mgmt_features/features.rb
management/azure_mgmt_features/lib/generated/azure_mgmt_features/models/feature_operations_list_result.rb
management/azure_mgmt_features/lib/generated/azure_mgmt_features/models/feature_properties.rb
management/azure_mgmt_features/lib/generated/azure_mgmt_features/models/feature_result.rb
management/azure_mgmt_locks/lib/generated/azure_mgmt_locks/management_lock_client.rb
management/azure_mgmt_locks/lib/generated/azure_mgmt_locks/management_locks.rb
management/azure_mgmt_locks/lib/generated/azure_mgmt_locks/models/management_lock_list_result.rb
management/azure_mgmt_locks/lib/generated/azure_mgmt_locks/models/management_lock_object.rb
management/azure_mgmt_locks/lib/generated/azure_mgmt_locks/models/management_lock_owner.rb
management/azure_mgmt_policy/lib/generated/azure_mgmt_policy/models/policy_assignment.rb
management/azure_mgmt_policy/lib/generated/azure_mgmt_policy/models/policy_assignment_list_result.rb
management/azure_mgmt_policy/lib/generated/azure_mgmt_policy/models/policy_definition.rb
management/azure_mgmt_policy/lib/generated/azure_mgmt_policy/models/policy_definition_list_result.rb
management/azure_mgmt_policy/lib/generated/azure_mgmt_policy/policy_assignments.rb
management/azure_mgmt_policy/lib/generated/azure_mgmt_policy/policy_client.rb
management/azure_mgmt_policy/lib/generated/azure_mgmt_policy/policy_definitions.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/models/location.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/models/location_list_result.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/models/subscription.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/models/subscription_list_result.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/models/subscription_policies.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/models/tenant_id_description.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/models/tenant_list_result.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/subscription_client.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/subscriptions.rb
management/azure_mgmt_subscriptions/lib/generated/azure_mgmt_subscriptions/tenants.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/670

Automatic PR from RestAPI-PR670

---

management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/analysis_services_management_client.rb
management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/models/analysis_services_server.rb
management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/models/analysis_services_server_update_parameters.rb
management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/models/analysis_services_servers.rb
management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/models/resource_sku.rb
management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/models/server_administrators.rb
management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/servers.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/722

Automatic PR from RestAPI-PR722

---

management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/artifact_operations.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/artifact_source_operations.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/cost_operations.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/custom_image_operations.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/formula_operations.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/gallery_image_operations.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/lab_operations.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/models/formula_properties_from_vm.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/models/parameter_info.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/models/policy_set_result.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/models/subnet.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/models/subnet_override.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/models/subscription_notification.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/models/subscription_notification_properties.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/policy_operations.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/policy_set.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/schedule_operations.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/virtual_machine.rb
management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/virtual_network_operations.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/718

Automatic PR from RestAPI-PR718

---

management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/consumer_groups.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/event_hub_management_client.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/event_hubs.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/consumer_group_create_or_update_parameters.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/consumer_group_list_result.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/consumer_group_resource.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/event_hub_create_or_update_parameters.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/event_hub_list_result.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/event_hub_properties.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/event_hub_resource.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/namespace_create_or_update_parameters.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/namespace_list_result.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/namespace_resource.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/regenerate_keys_parameters.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/resource_list_keys.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/shared_access_authorization_rule_create_or_update_parameters.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/shared_access_authorization_rule_list_result.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/shared_access_authorization_rule_resource.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/models/sku.rb
management/azure_mgmt_event_hub/lib/generated/azure_mgmt_event_hub/namespaces.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/677

Automatic PR from RestAPI-PR677

---

Rakefile
azure_sdk/azure_sdk.gemspec
management/azure_mgmt_service_bus/spec/namespaces_spec.rb
management/azure_mgmt_service_bus/spec/queues_spec.rb
management/azure_mgmt_service_bus/spec/spec_helper.rb
management/azure_mgmt_service_bus/spec/vcr_cassettes/should_create_list_and_delete_namespace.yml
management/azure_mgmt_service_bus/spec/vcr_cassettes/should_create_list_and_delete_queues.yml

Issue: #591 
Bug resolution verification for https://github.com/Azure/azure-rest-api-specs/issues/464

Prepare to include azure_mgmt_service_bus into next ARM release

---

management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/cdn_management_client.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/custom_domains.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/endpoints.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/check_name_availability_output.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/custom_domain.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/endpoint.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/endpoint_update_parameters.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/operation_display.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/origin.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/origin_list_result.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/profile.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/origins.rb
management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/profiles.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/725

Automatic PR from RestAPI-PR725

---

management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/azure_mlweb_services_management_client.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/asset_item.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/column_format.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/column_specification.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/commitment_plan.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/diagnostics_configuration.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/graph_edge.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/graph_node.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/graph_package.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/machine_learning_workspace.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/paginated_web_services_list.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/provisioning_state.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/realtime_configuration.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/service_input_output_specification.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/storage_account.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/table_specification.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/web_service.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/models/web_service_properties.rb
management/azure_mgmt_machine_learning/lib/generated/azure_mgmt_machine_learning/web_services.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/719

Automatic PR from RestAPI-PR719

---

ChangeLog.md
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/queue_create_or_update_parameters.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/queue_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/subscription_create_or_update_parameters.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/subscription_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/topic_create_or_update_parameters.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/topic_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/namespaces.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/queues.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/service_bus_management_client.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/subscriptions.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/topics.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/version.rb

Part of the feature work https://github.com/Azure/azure-sdk-for-ruby/issues/517

Regen azure_mgmt_service_bus using AutoRest.1.0.0-Nightly20161114

---

management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_create_parameters.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_resource.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/models/redis_update_parameters.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/redis_management_client.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/746

Automatic PR from RestAPI-PR746

---

runtime/ms_rest_azure/lib/ms_rest_azure/azure_environment.rb

Correcting typo in storage_endpoint_suffix key for azure environments

---

management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/patch_schedules.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/redis.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/782

Automatic PR from RestAPI-PR782

---

Rakefile
swagger_to_sdk_config.json

Related to https://github.com/Azure/azure-sdk-for-ruby/issues/651 
@vishrutshah @veronicagg @salameer Please review and approve.

Changed the Network service SDK generation to composite swagger file

---

management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services.rb
management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/analysis_services_management_client.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/810

Automatic PR from RestAPI-PR810

---

management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/virtual_machine_scale_set_vm.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/789

Automatic PR from RestAPI-PR789

---

management/azure_mgmt_locks/lib/generated/azure_mgmt_locks/management_lock_client.rb
management/azure_mgmt_locks/lib/generated/azure_mgmt_locks/management_locks.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/666

Automatic PR from RestAPI-PR666

---

management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/patch_schedules.rb
management/azure_mgmt_redis/lib/generated/azure_mgmt_redis/redis.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/839

Automatic PR from RestAPI-PR839

---

runtime/ms_rest/lib/ms_rest/service_client.rb

Related to https://github.com/Azure/autorest/pull/1677
Related to Azure/azure-sdk-for-ruby#613
@veronicagg @vishrutshah @salameer Please review.

Make credentials nil by default

---

runtime/ms_rest/lib/ms_rest/http_operation_request.rb

Fix issue #639

---

management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/models/tag_count.rb
management/azure_mgmt_resources/lib/generated/azure_mgmt_resources/resource_management_client.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/846

Automatic PR from RestAPI-PR846

---

management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/error_response.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/monetary_commitment.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/monetary_credit.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/recurring_charge.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/usage_aggregates.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/usage_management_client.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/824

Automatic PR from RestAPI-PR824

---

README.md
runtime/ms_rest_azure/lib/ms_rest_azure/azure_service_client.rb

@vishrutshah @salameer Please review

Handle the custom desrialization block correctly

---

.travis.yml
scripts/latest_runtime.sh

Allow failure while testing latest runtime

---

README.md
runtime/ms_rest/CHANGELOG.md
runtime/ms_rest/README.md
runtime/ms_rest/lib/ms_rest/version.rb
runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/README.md
runtime/ms_rest_azure/lib/ms_rest_azure/azure_service_client.rb
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb
runtime/ms_rest_azure/ms_rest_azure.gemspec

@veronicagg Could you please review when you get a chance. Thanks! 
Also, let me know if i missed something from our yesterday's discussion. :)

Preparing to release runtime ms_rest 0.6.3 & ms_rest_azure 0.7.0

---

ChangeLog.md
azure_sdk/azure_sdk.gemspec
azure_sdk/lib/azure_sdk/version.rb

- Update ChangeLog for release milestone v0.9.0-arm
- Update azure_sdk version to 0.9.0 and azure-storage to 0.11.5.preview
For https://github.com/Azure/azure-sdk-for-ruby/issues/673

Update ChangeLog for release milestone v0.9.0-arm

---

management/azure_mgmt_datalake_store/lib/generated/azure_mgmt_datalake_store.rb
management/azure_mgmt_datalake_store/lib/generated/azure_mgmt_datalake_store/models/data_lake_store_account.rb
management/azure_mgmt_datalake_store/lib/generated/azure_mgmt_datalake_store/models/data_lake_store_account_update_parameters.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/927

Automatic PR from RestAPI-PR927

---

management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/meter_info.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/monetary_commitment.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/monetary_credit.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/offer_term_info.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/recurring_charge.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/models/resource_rate_card_info.rb
management/azure_mgmt_commerce/lib/generated/azure_mgmt_commerce/rate_card.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/884

Automatic PR from RestAPI-PR884

---

management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/container_services.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/937

Automatic PR from RestAPI-PR937

---

runtime/ms_rest_azure/lib/ms_rest_azure/active_directory_service_settings.rb
runtime/ms_rest_azure/lib/ms_rest_azure/azure_environment.rb
runtime/ms_rest_azure/spec/active_directory_service_settings_spec.rb
runtime/ms_rest_azure/spec/azure_environment_spec.rb

Related to https://github.com/Azure/azure-sdk-for-ruby/issues/600 
Changed the names to be in sync with  azure-cli and azure-powershell.
@veronicagg @vishrutshah @salameer Please review

Changed the name of the Azure Environments

---

swagger_to_sdk_config.json

@vishrutshah @veronicagg @salameer Please review and approve

Upgrade to new version

---

runtime/ms_rest_azure/lib/ms_rest_azure/azure_service_client.rb

Related to https://github.com/Azure/azure-sdk-for-ruby/issues/701 
Tested the specified scenario and all the other gems by modifying gemspec and running rspec. 
@vishrutshah @veronicagg @salameer Please review

Added Accept header to the Ruby SDK

---

README.md

Remove maintainers section

---

runtime/ms_rest/CHANGELOG.md
runtime/ms_rest/README.md
runtime/ms_rest/lib/ms_rest/service_client.rb
runtime/ms_rest/lib/ms_rest/version.rb
runtime/ms_rest/spec/ms_rest_spec.rb

Related to::
1. https://github.com/Azure/vagrant-azure/issues/182
2. https://github.com/Azure/vagrant-azure/pull/183
Made the change locally and tested with our rspec and confirmed none of our tests are breaking. Will send the release related changes in a separate PR. 
@devigned @vishrutshah @veronicagg @salameer Please review and approve.

Fix for the faraday issue

---

management/azure_mgmt_network/lib/generated/azure_mgmt_network/application_gateways.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/bgp_service_communities.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/express_route_circuit_authorizations.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/express_route_circuit_peerings.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/express_route_circuits.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/express_route_service_providers.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/load_balancers.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/local_network_gateways.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/models/local_network_gateway.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/models/virtual_network_gateway.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/models/virtual_network_gateway_ipconfiguration.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/models/virtual_network_gateway_sku.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_interfaces.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_management_client.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_security_groups.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_watchers.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/packet_captures.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/public_ipaddresses.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/route_filter_rules.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/route_filters.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/route_tables.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/routes.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/security_rules.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/subnets.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/usages.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/virtual_network_gateway_connections.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/virtual_network_gateways.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/virtual_network_peerings.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/virtual_networks.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1063

Automatic PR from RestAPI-PR1063

---

management/azure_mgmt_recovery_services/lib/generated/azure_mgmt_recovery_services/vaults.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1074

Automatic PR from RestAPI-PR1074

---

ChangeLog.md
lib/azure/version.rb

@yaxia @seguler @vishrutshah @veronicagg @salameer @devigned Could you please review and approve?

Preparing for release of azure gem v0.7.8

---

management/azure_mgmt_network/lib/generated/azure_mgmt_network/application_gateways.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/bgp_service_communities.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/express_route_circuit_authorizations.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/express_route_circuit_peerings.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/express_route_circuits.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/express_route_service_providers.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/load_balancers.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/local_network_gateways.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_interfaces.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_management_client.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_security_groups.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_watchers.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/packet_captures.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/public_ipaddresses.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/route_filter_rules.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/route_filters.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/route_tables.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/routes.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/security_rules.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/subnets.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/usages.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/virtual_network_gateway_connections.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/virtual_network_gateways.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/virtual_network_peerings.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/virtual_networks.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1088

Automatic PR from RestAPI-PR1088

---

management/azure_mgmt_network/lib/generated/azure_mgmt_network/models/virtual_network_gateway_sku.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/models/virtual_network_gateway_sku_name.rb
management/azure_mgmt_network/lib/generated/azure_mgmt_network/models/virtual_network_gateway_sku_tier.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1130

Automatic PR from RestAPI-PR1130

---

.travis.yml
ChangeLog.md
lib/azure/version.rb

@veronicagg @vishrutshah @salameer Please review and approve. 
Please refer https://github.com/Azure/azure-sdk-for-ruby/issues/755 for more context.

 Preparing for release of azure gem v0.7.9

---

management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/models/database.rb
management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/models/elastic_pool_activity.rb
management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/models/service_objective_capability.rb
management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/models/slo_usage_metric.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1107

Automatic PR from RestAPI-PR1107

---

management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/namespace_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/queue_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/shared_access_authorization_rule_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/subscription_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/topic_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/models/tracked_resource.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/namespaces.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/operations.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/queues.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/subscriptions.rb
management/azure_mgmt_service_bus/lib/generated/azure_mgmt_service_bus/topics.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1138

Automatic PR from RestAPI-PR1138

---

management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/databases.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1166

Automatic PR from RestAPI-PR1166

---

management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/servers.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1184

Automatic PR from RestAPI-PR1184

---

management/azure_mgmt_graph/lib/generated/azure_mgmt_graph/models/user.rb
management/azure_mgmt_graph/lib/generated/azure_mgmt_graph/models/user_create_parameters.rb
management/azure_mgmt_graph/lib/generated/azure_mgmt_graph/models/user_update_parameters.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1244

Automatic PR from RestAPI-PR1244

---

README.md

They look better on hi-res displays

Use retina travis badge

---

management/azure_mgmt_traffic_manager/lib/generated/azure_mgmt_traffic_manager/endpoints.rb
management/azure_mgmt_traffic_manager/lib/generated/azure_mgmt_traffic_manager/profiles.rb

Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1265

Automatic PR from RestAPI-PR1265

---

runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb

This is to handle the bug fix related to polling state for Adobe customer. 
Please review and approve.

Release ms_rest_azure to v0.8.1

---

management/azure_mgmt_insights/README.md
management/azure_mgmt_insights/lib/generated/azure_mgmt_insights/version.rb

Final changes to the Insights gem

---

runtime/ms_rest/lib/ms_rest/jsonable.rb
runtime/ms_rest/spec/jsonable_spec.rb

This is a minor bug fix. Currently no code uses this. Please review and approve

Code changes for serialization/deserialization

---

runtime/ms_rest/CHANGELOG.md
runtime/ms_rest/lib/ms_rest/version.rb

Code changes to bump ms_rest version 0.7.1

---

swagger_to_sdk_config.json

The azure-arm flag is missing in the config file. Also, the tag values need to be modified for correct generation. 
Ref: https://github.com/Azure/azure-sdk-for-python/blob/master/swagger_to_sdk_config.json
Please review and approve

Fix issues with config file

---

.travis.yml
ChangeLog.md
README.md
azure.gemspec
lib/azure/version.rb

Tested with ruby 2.0, 2.1, 2.2, 2.3, 2.4 versions

Nokogiri version fix

---

Rakefile

Reverts Azure/azure-sdk-for-ruby#1004

Revert "Revert "Revert "[rake arm:release] Rescue error while publishing (#97…"

---

ChangeLog.md
README.md

@salameer @veronicagg @vishrutshah @devigned Please review.

Doc updates

---

runtime/ms_rest/CHANGELOG.md
runtime/ms_rest/README.md
runtime/ms_rest/lib/ms_rest/version.rb
runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/README.md
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb
runtime/ms_rest_azure/ms_rest_azure.gemspec

Please review and approve. 
Should be merged after merge of https://github.com/Azure/azure-sdk-for-ruby/pull/1119

Bump versions of ms_rest & ms_rest_azure

---

config.json
swagger_to_sdk_config.json

Updating swagger_to_sdk_config due to failure https://travis-ci.org/Azure/azure-rest-api-specs/jobs/318930236#L675

fixing swagger_to_sdk_config

---

data/azure_cognitiveservices_computervision/lib/1.0/generated/azure_cognitiveservices_computervision/computer_vision_client.rb
data/azure_cognitiveservices_contentmoderator/lib/1.0/generated/azure_cognitiveservices_contentmoderator/image_moderation.rb
data/azure_cognitiveservices_contentmoderator/lib/1.0/generated/azure_cognitiveservices_contentmoderator/list_management_image.rb
data/azure_cognitiveservices_contentmoderator/lib/1.0/generated/azure_cognitiveservices_contentmoderator/reviews.rb
data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/face.rb
data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/face_list.rb
data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/person.rb
management/azure_mgmt_automation/lib/2015-10-31/generated/azure_mgmt_automation/runbook_draft_operations.rb

Regen SDK after Stream fix

---

runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb

Bump ms_rest_azure version to 0.10.3

---

management/azure_mgmt_graph/README.md
management/azure_mgmt_graph/lib/version.rb

Code to bump azure_mgmt_graph

---

swagger_to_sdk_config.json

@sarangan12 I need this for https://github.com/Azure/azure-rest-api-specs/pull/2514 and this doesn't hurt you at all (since this is new parameter you don't use). So should be safe to merge :)
If you have concern, please let me know.
Thanks!
FYI @salameer

SwaggerToSdk ready for recent work

---

runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb
runtime/ms_rest_azure/spec/msi_token_provider_spec.rb

@yugangw-msft @salameer Please review and approve

Msi Imds task

---

runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb

Added User Agent Information.....
@yugangw-msft @salameer FYI...

Adding User Agent Information

---

runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb

@salameer @yugangw-msft FYI....

Bump ms_rest_azure version to 0.10.4

---

runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb

@yugangw-msft @salameer Please review and approve.

Adding new error status codes for IMDS MSI Token

---

runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb

@yugangw-msft @salameer FYI.....

Bump ms_rest_azure to version 0.10.5

---

runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb

@anuchandy @salameer Please review and approve.

Add Url Encode in IMDS

---

CODEOWNERS

Created Codeowners file

---

ChangeLog.md
azure_sdk/lib/azure_sdk/version.rb
azure_sdk/lib/latest/modules/containerservice_profile_module.rb
config/GEMS_TO_RELEASE
config/GEM_VERSIONS
config/config.json
management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/container_service_client.rb
management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service.rb
management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/container_service_client.rb
management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/container_services.rb
management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service.rb
management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/container_service_client.rb
management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/container_services.rb
management/azure_mgmt_container_service/lib/profiles/latest/modules/containerservice_profile_module.rb
management/azure_mgmt_container_service/lib/version.rb

Container service fix

---

runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb

@yugangw-msft Could you please review and approve it?
@salameer FYI.....

Add 410 Error code to IMDS and Bump version 0.10.7

---

runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/lib/ms_rest_azure/async_operation_status.rb
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb
runtime/ms_rest_azure/spec/polling_state_spec.rb

@salameer @veronicagg FYI...........

Add case insensitive check to operation status and bump ms_rest_azure

---

management/azure_mgmt_network/lib/2015-06-15/generated/azure_mgmt_network/models/network_interface_ipconfiguration.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3200

[AutoPR network/resource-manager] Add primary flag to 2015-06-15  NetworkInterfaceIPConfiguration 

---

data/azure_cognitiveservices_computervision/lib/1.0/generated/azure_cognitiveservices_computervision/computer_vision_client.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3222

[AutoPR cognitiveservices/data-plane/ComputerVision] Add Spanish as an option as ServiceLanguage for ComputerVision

---

management/azure_mgmt_container_instance/lib/azure_mgmt_container_instance.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3231

[AutoPR containerinstance/resource-manager] Container Instance - Fix Mistake in June Update

---

management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/data_disk.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/osdisk.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/rollback_status_info.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/virtual_machine_scale_set_osdisk.rb
management/azure_mgmt_compute/lib/azure_mgmt_compute.rb

Created to accumulate context: compute/resource-manager

[AutoPR] compute/resource-manager

---

data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_tag.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3259

[AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision add tag.hint

---

management/azure_mgmt_storage/lib/2015-05-01-preview/generated/azure_mgmt_storage/storage_management_client.rb
management/azure_mgmt_storage/lib/2015-06-15/generated/azure_mgmt_storage/storage_management_client.rb
management/azure_mgmt_storage/lib/2016-01-01/generated/azure_mgmt_storage/storage_management_client.rb
management/azure_mgmt_storage/lib/2016-12-01/generated/azure_mgmt_storage/storage_management_client.rb
management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/storage_management_client.rb
management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/storage_management_client.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/endpoints.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/storage_account.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/storage_account_create_parameters.rb
management/azure_mgmt_storage/lib/azure_mgmt_storage.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3289

[AutoPR storage/resource-manager] [Storage] Support HDFS feature and web endpoint in Account properties 

---

management/azure_mgmt_storage/lib/2015-05-01-preview/generated/azure_mgmt_storage/version.rb
management/azure_mgmt_storage/lib/2015-06-15/generated/azure_mgmt_storage/version.rb
management/azure_mgmt_storage/lib/2016-01-01/generated/azure_mgmt_storage/version.rb
management/azure_mgmt_storage/lib/2016-12-01/generated/azure_mgmt_storage/version.rb
management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/version.rb
management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/version.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/version.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3310

[AutoPR storage/resource-manager] Minor update to version

---

management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/metric_specification.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/name_availability.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/name_availability_parameters.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/operation.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/operation_display.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/operation_list.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/operation_properties.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/regenerate_key_parameters.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/resource.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/resource_sku.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/service_specification.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/signal_rcreate_or_update_properties.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/signal_rcreate_parameters.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/signal_rkeys.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/signal_rresource.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/signal_rresource_list.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/signal_rupdate_parameters.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/tracked_resource.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/operations.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/signal_r.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/signal_rmanagement_client.rb
management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/version.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3318

[AutoPR signalr/resource-manager] Add a new tier for Azure SignalR serivce

---

management/azure_mgmt_service_bus/lib/2017-04-01/generated/azure_mgmt_service_bus/models/arm_disaster_recovery.rb
management/azure_mgmt_service_bus/lib/2017-04-01/generated/azure_mgmt_service_bus/models/migration_config_properties.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3330

[AutoPR servicebus/resource-manager] ServiceBus: Removed space from pendingReplicationOperationsCount

---

management/azure_mgmt_network/lib/2015-05-01-preview/generated/azure_mgmt_network/models/azure_async_operation_result.rb
management/azure_mgmt_network/lib/2016-03-30/generated/azure_mgmt_network/models/azure_async_operation_result.rb
management/azure_mgmt_network/lib/2016-06-01/generated/azure_mgmt_network/models/azure_async_operation_result.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3344

[AutoPR network/resource-manager] Fixed typos. Fixes issue 1770 in .NET SDK

---

azure_sdk/lib/latest/modules/monitor_profile_module.rb
management/azure_mgmt_monitor/lib/2015-04-01/generated/azure_mgmt_monitor.rb
management/azure_mgmt_monitor/lib/2015-04-01/generated/azure_mgmt_monitor/models/recurrence.rb
management/azure_mgmt_monitor/lib/profiles/latest/modules/monitor_profile_module.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3468

[AutoPR monitor/resource-manager] updated description of recurrent frequency

---

runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb

@yugangw-msft Could you please review

MSI Retry User enables max retry fix

---

management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/database_vulnerability_assessment.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3579

[AutoPR sql/resource-manager] fix SQL VA command copy paste typo

---

azure_sdk/lib/latest/modules/monitor_profile_module.rb
management/azure_mgmt_monitor/lib/2015-04-01/generated/azure_mgmt_monitor.rb
management/azure_mgmt_monitor/lib/2015-04-01/generated/azure_mgmt_monitor/models/recurrence.rb
management/azure_mgmt_monitor/lib/profiles/latest/modules/monitor_profile_module.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3586

[AutoPR monitor/resource-manager] [Monitor] Fix issue #3585: revert previous commit since it is a brealing change

---

management/azure_mgmt_api_management/lib/2018-01-01/generated/azure_mgmt_api_management/models/certificate_configuration.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3609

[AutoPR apimanagement/resource-manager] Bug fix on readonly property

---

management/azure_mgmt_api_management/lib/2018-01-01/generated/azure_mgmt_api_management/models/hostname_configuration.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3633

[AutoPR apimanagement/resource-manager] Make 2018-01-01 as default for all clients

---

management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/data_disk.rb
management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/osdisk.rb
management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/data_disk.rb
management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/osdisk.rb
management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/data_disk.rb
management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/osdisk.rb
management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/virtual_machine_scale_set_data_disk.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/data_disk.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/osdisk.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/virtual_machine_scale_set_data_disk.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/data_disk.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/osdisk.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/virtual_machine_scale_set_data_disk.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3814

[AutoPR compute/resource-manager] Fix description for disk size

---

management/azure_mgmt_logic/lib/2018-07-01-preview/generated/azure_mgmt_logic/integration_account_sessions.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3868

[AutoPR logic/resource-manager] Remove default response from Sessions

---

management/azure_mgmt_sql/lib/2014-04-01/generated/azure_mgmt_sql/models/database_security_alert_policy.rb
management/azure_mgmt_sql/lib/2015-05-01-preview/generated/azure_mgmt_sql/models/managed_instance.rb
management/azure_mgmt_sql/lib/2015-05-01-preview/generated/azure_mgmt_sql/models/managed_instance_update.rb
management/azure_mgmt_sql/lib/2015-05-01-preview/generated/azure_mgmt_sql/models/sku.rb
management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/server_security_alert_policy.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3875

[AutoPR sql/resource-manager] Swagger Changes to Add DnsZonePartner and Collation into Managed Instance 

---

management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/boot_diagnostics.rb
management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/boot_diagnostics_instance_view.rb
management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/diagnostics_profile.rb
management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/virtual_machine_instance_view.rb
management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/virtual_machine_scale_set_vminstance_view.rb
management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/boot_diagnostics.rb
management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/boot_diagnostics_instance_view.rb
management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/diagnostics_profile.rb
management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/virtual_machine_instance_view.rb
management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/virtual_machine_scale_set_vminstance_view.rb
management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/boot_diagnostics.rb
management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/boot_diagnostics_instance_view.rb
management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/diagnostics_profile.rb
management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/virtual_machine_instance_view.rb
management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/virtual_machine_scale_set_vminstance_view.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/boot_diagnostics.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/boot_diagnostics_instance_view.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/diagnostics_profile.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/virtual_machine_instance_view.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/virtual_machine_scale_set_vminstance_view.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/boot_diagnostics.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/boot_diagnostics_instance_view.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/diagnostics_profile.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/virtual_machine_instance_view.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/virtual_machine_scale_set_vminstance_view.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3983

[AutoPR compute/resource-manager] Swagger change for adding status to BootDiagnosticsInstanceView

---

runtime/ms_rest/CHANGELOG.md
runtime/ms_rest/README.md
runtime/ms_rest/lib/ms_rest/http_operation_request.rb
runtime/ms_rest/lib/ms_rest/version.rb

@veronicagg @devigned Please review and approve.
@salameer FYI...

Code change to retry based on retry-after header

---

README.md

@salameer @veronicagg @nicolasleger  FYI....
Duplicate of https://github.com/Azure/azure-sdk-for-ruby/pull/1269

Fix Travis Link

---

azure_sdk/lib/azure_sdk.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4303

[AutoPR automation/resource-manager] Reverting change: Replacing PartialSync for IncrementalSync for sync type and updating examples.

---

azure_sdk/lib/azure_sdk.rb
management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/backup_long_term_retention_policy.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4313

[AutoPR sql/resource-manager] Fixed spelling mistake in SQL documentation

---

azure_sdk/lib/azure_sdk.rb
management/azure_mgmt_compute/lib/azure_mgmt_compute.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4299

[AutoPR compute/resource-manager] Added Reimage API support for ephemeral os disks in single VM

---

azure_sdk/lib/azure_sdk.rb
management/azure_mgmt_container_service/lib/azure_mgmt_container_service.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4322

[AutoPR containerservices/resource-manager] ACS multiapi for Python

---

azure_sdk/lib/azure_sdk.rb
management/azure_mgmt_web/lib/azure_mgmt_web.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4295

[AutoPR web/resource-manager] Fix network trace API REST format

---

azure_sdk/lib/azure_sdk.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4334

[AutoPR cost-management/resource-manager] Microsoft.CostManagement - Add supression command into readme

---

azure_sdk/lib/azure_sdk.rb
management/azure_mgmt_storage/lib/azure_mgmt_storage.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4316

[AutoPR storage/resource-manager] Support for SRP BlobServiceProperties API

---

Gemfile
scripts/pr_build_drop_publisher.rb

Code changes for updating Drop comment in PR

---

scripts/pr_build_drop_publisher.rb

Adding Installation Instructions

---

azure_sdk/lib/azure_sdk.rb
management/azure_mgmt_api_management/lib/azure_mgmt_api_management.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4384

[AutoPR apimanagement/resource-manager] Move version 2018-01-01 to stable folder

---

management/azure_mgmt_container_registry/lib/azure_mgmt_container_registry.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4389

[AutoPR containerregistry/resource-manager] ACR: Add contextAccessToken to Task step

---

Rakefile
generators/metadatagen/src/metadatagen.rb
generators/metadatagen/src/metadatagen_options_parser.rb
generators/metadatagen/src/resources/.rspec
generators/metadatagen/src/resources/LICENSE.txt
generators/metadatagen/src/resources/Rakefile
generators/metadatagen/src/resources/require_file.rb
generators/metadatagen/src/resources/spec_helper.rb
generators/metadatagen/src/resources/templates/gemspec_template.template
generators/metadatagen/src/resources/templates/module_definition_template.template
generators/metadatagen/src/resources/templates/version_template.template
generators/profilegen/src/profile_generator_client.rb

Gen folder structure if necessary

---

management/azure_mgmt_web/lib/2015-04-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
management/azure_mgmt_web/lib/2015-04-01/generated/azure_mgmt_web/models/slot_swap_status.rb
management/azure_mgmt_web/lib/2015-04-01/generated/azure_mgmt_web/models/user.rb
management/azure_mgmt_web/lib/2015-08-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
management/azure_mgmt_web/lib/2015-08-01/generated/azure_mgmt_web/models/slot_swap_status.rb
management/azure_mgmt_web/lib/2015-08-01/generated/azure_mgmt_web/models/user.rb
management/azure_mgmt_web/lib/2016-03-01/generated/azure_mgmt_web/models/csm_usage_quota.rb
management/azure_mgmt_web/lib/2016-03-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
management/azure_mgmt_web/lib/2016-03-01/generated/azure_mgmt_web/models/slot_swap_status.rb
management/azure_mgmt_web/lib/2016-03-01/generated/azure_mgmt_web/models/user.rb
management/azure_mgmt_web/lib/2016-08-01/generated/azure_mgmt_web/models/csm_usage_quota.rb
management/azure_mgmt_web/lib/2016-08-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
management/azure_mgmt_web/lib/2016-08-01/generated/azure_mgmt_web/models/slot_swap_status.rb
management/azure_mgmt_web/lib/2016-08-01/generated/azure_mgmt_web/models/user.rb
management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/csm_usage_quota.rb
management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/slot_swap_status.rb
management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/user.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4504

[AutoPR web/resource-manager] typo: Fix Microsoft.Web/CommonDefinitions.json

---

management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/app_service_environment_patch_resource.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4527

[AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/AppServiceEnvironments

---

management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/blob_containers.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4551

[AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/blob

---

management/azure_mgmt_storage/lib/2016-12-01/generated/azure_mgmt_storage/models/list_service_sas_response.rb
management/azure_mgmt_storage/lib/2016-12-01/generated/azure_mgmt_storage/models/service_sas_parameters.rb
management/azure_mgmt_storage/lib/2016-12-01/generated/azure_mgmt_storage/models/storage_account_check_name_availability_parameters.rb
management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/models/dimension.rb
management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/models/list_service_sas_response.rb
management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/models/service_sas_parameters.rb
management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/models/storage_account_check_name_availability_parameters.rb
management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/models/storage_account_regenerate_key_parameters.rb
management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/models/dimension.rb
management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/models/list_service_sas_response.rb
management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/models/service_sas_parameters.rb
management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/models/storage_account_check_name_availability_parameters.rb
management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/models/storage_account_regenerate_key_parameters.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/blob_containers.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/dimension.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/list_service_sas_response.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/service_sas_parameters.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/storage_account_check_name_availability_parameters.rb
management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/storage_account_regenerate_key_parameters.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4549

[AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/storage

---

management/azure_mgmt_network/lib/2015-06-15/generated/azure_mgmt_network/express_route_circuits.rb
management/azure_mgmt_network/lib/2017-09-01/generated/azure_mgmt_network/models/express_route_circuit_peering_config.rb
management/azure_mgmt_network/lib/2017-10-01/generated/azure_mgmt_network/models/express_route_circuit_peering_config.rb
management/azure_mgmt_network/lib/2017-11-01/generated/azure_mgmt_network/models/express_route_circuit_peering_config.rb
management/azure_mgmt_network/lib/2018-01-01/generated/azure_mgmt_network/models/express_route_circuit_peering_config.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4530

[AutoPR network/resource-manager] typo: network/resource-manager/Microsoft.Network/expressRouteCircuit

---

management/azure_mgmt_billing/lib/2017-04-24-preview/generated/azure_mgmt_billing/models/invoice.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4632

[AutoPR billing/resource-manager] typo: Microsoft.Billing

---

management/azure_mgmt_web/lib/2015-08-01/generated/azure_mgmt_web/models/app_service_certificate_collection.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4813

[AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.CertificateRegistration

---

management/azure_mgmt_storage/lib/2015-06-15/generated/azure_mgmt_storage/models/storage_account_check_name_availability_parameters.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4786

[AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage

---

data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/face.rb
data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/models/find_similar_request.rb
data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/snapshot_operations.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5094

[AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Refine the documentation for Face API's new Snapshot features. 

---

management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/hardware_profile.rb
management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/vault_certificate.rb
management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/hardware_profile.rb
management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/vault_certificate.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/hardware_profile.rb
management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/vault_certificate.rb
management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/vault_certificate.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5159

[AutoPR compute/resource-manager] fixes for reference documentation

---

management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network.rb
management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network/models/azure_firewall.rb
management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network/models/azure_firewall_rcaction.rb
management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network/models/azure_firewall_threat_intel_mode.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5143

[AutoPR network/resource-manager] Threat Intel changes for Azure Firewall

---

management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network/models/express_route_circuit_sku.rb
management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network/models/express_route_circuit_sku_tier.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5317

[AutoPR network/resource-manager] Add support for Local Sku

---

management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network/express_route_circuit_connections.rb
management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network/models/application_gateway.rb
management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network/models/application_gateway_autoscale_configuration.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5265

[AutoPR network/resource-manager] [Hub Generated] Review request for Microsoft.Network to add version 2018-12-01

---

management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/osprofile.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5335

[AutoPR compute/resource-manager] update description.

---

management/azure_mgmt_event_hub/lib/2017-04-01/generated/azure_mgmt_event_hub/namespaces.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5360

[AutoPR eventhub/resource-manager] EventHub : corrected typo 

---

management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/models/audio_analyzer_preset.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/models/built_in_standard_encoder_preset.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/models/encoder_named_preset.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/models/h264layer.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5413

[AutoPR mediaservices/resource-manager] Add preset enum ContentAwareEncodingExperimental

---

data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/application.rb
data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/application_base.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5456

[AutoPR graphrbac/data-plane] typo: informations -> information about

---

management/azure_mgmt_consumption/lib/2019-01-01/generated/azure_mgmt_consumption/models/budget.rb
management/azure_mgmt_consumption/lib/2019-01-01/generated/azure_mgmt_consumption/models/time_grain_type.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5599

[AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version stable/2019-01-01

---

azure_sdk/lib/latest/modules/autosuggest_profile_module.rb
azure_sdk/lib/latest/modules/computervision_profile_module.rb
azure_sdk/lib/latest/modules/contentmoderator_profile_module.rb
azure_sdk/lib/latest/modules/customsearch_profile_module.rb
azure_sdk/lib/latest/modules/customvisiontraining_profile_module.rb
azure_sdk/lib/latest/modules/entitysearch_profile_module.rb
azure_sdk/lib/latest/modules/face_profile_module.rb
azure_sdk/lib/latest/modules/imagesearch_profile_module.rb
azure_sdk/lib/latest/modules/localsearch_profile_module.rb
azure_sdk/lib/latest/modules/newssearch_profile_module.rb
azure_sdk/lib/latest/modules/qnamaker_profile_module.rb
azure_sdk/lib/latest/modules/spellcheck_profile_module.rb
azure_sdk/lib/latest/modules/sql_profile_module.rb
azure_sdk/lib/latest/modules/sqlvirtualmachine_profile_module.rb
azure_sdk/lib/latest/modules/storage_profile_module.rb
azure_sdk/lib/latest/modules/storsimple8000series_profile_module.rb
azure_sdk/lib/latest/modules/streamanalytics_profile_module.rb
azure_sdk/lib/latest/modules/textanalytics_profile_module.rb
azure_sdk/lib/latest/modules/trafficmanager_profile_module.rb
azure_sdk/lib/latest/modules/videosearch_profile_module.rb
azure_sdk/lib/latest/modules/visualsearch_profile_module.rb
azure_sdk/lib/latest/modules/web_profile_module.rb
azure_sdk/lib/latest/modules/websearch_profile_module.rb
management/azure_mgmt_sql/lib/2015-05-01-preview/generated/azure_mgmt_sql.rb
management/azure_mgmt_sql/lib/2015-05-01-preview/generated/azure_mgmt_sql/models/managed_instance.rb
management/azure_mgmt_sql/lib/2015-05-01-preview/generated/azure_mgmt_sql/models/managed_instance_update.rb
management/azure_mgmt_sql/lib/profiles/latest/modules/sql_profile_module.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5780

[AutoPR sql/resource-manager] Fix missing proxy override enum for managed instance swagger

---

runtime/ms_rest/CHANGELOG.md
runtime/ms_rest/lib/ms_rest/version.rb
runtime/ms_rest/ms_rest.gemspec
runtime/ms_rest_azure/CHANGELOG.md
runtime/ms_rest_azure/lib/ms_rest_azure/azure_operation_response.rb
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb
runtime/ms_rest_azure/ms_rest_azure.gemspec

@veronicagg & @salameer FYI.....

Add Ids & Fix Unf Ext version

---

management/azure_mgmt_media_services/lib/2018-03-30-preview/generated/azure_mgmt_media_services/assets.rb
management/azure_mgmt_media_services/lib/2018-03-30-preview/generated/azure_mgmt_media_services/content_key_policies.rb
management/azure_mgmt_media_services/lib/2018-03-30-preview/generated/azure_mgmt_media_services/models/list_container_sas_input.rb
management/azure_mgmt_media_services/lib/2018-06-01-preview/generated/azure_mgmt_media_services/assets.rb
management/azure_mgmt_media_services/lib/2018-06-01-preview/generated/azure_mgmt_media_services/content_key_policies.rb
management/azure_mgmt_media_services/lib/2018-06-01-preview/generated/azure_mgmt_media_services/models/list_container_sas_input.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/assets.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/content_key_policies.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/jobs.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/models/absolute_clip_time.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/models/filter_track_property_condition.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/models/presentation_time_range.rb
management/azure_mgmt_media_services/lib/2018-07-01/generated/azure_mgmt_media_services/transforms.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6145

[AutoPR mediaservices/resource-manager] typo: mediaservices/resource-manager/Microsoft.Media

---

management/azure_mgmt_notification_hubs/lib/2017-04-01/generated/azure_mgmt_notification_hubs/models/namespace_create_or_update_parameters.rb
management/azure_mgmt_notification_hubs/lib/2017-04-01/generated/azure_mgmt_notification_hubs/models/namespace_resource.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6420

[AutoPR notificationhubs/resource-manager] typo: notificationhubs

---

management/azure_mgmt_authorization/lib/2015-07-01/generated/azure_mgmt_authorization/classic_administrators.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6447

[AutoPR authorization/resource-manager] Forgot tiny clean-up

---

management/azure_mgmt_vmwarecloudsimple/lib/2019-04-01/generated/azure_mgmt_vmwarecloudsimple/dedicated_cloud_service_operations.rb

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6415

[AutoPR vmwarecloudsimple/resource-manager] typo: vmwarecloudsimple

---

runtime/ms_rest/lib/ms_rest/version.rb
runtime/ms_rest_azure/lib/ms_rest_azure/credentials/application_token_provider.rb
runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb
runtime/ms_rest_azure/lib/ms_rest_azure/version.rb
runtime/ms_rest_azure/ms_rest_azure.gemspec
runtime/ms_rest_azure/spec/application_token_provider_spec.rb
runtime/ms_rest_azure/spec/msi_token_provider_spec.rb

Expose token expires on in ms_rest_azure
Bump the version for release

Expose token expires on in ms_rest_azure

---

runtime/ms_rest_azure/lib/ms_rest_azure/azure_environment.rb

update aad endpoint in US cloud

---

ChangeLog.md
azure_sdk/lib/azure_sdk/version.rb
config/GEMS_TO_RELEASE
config/GEM_VERSIONS
data/azure_key_vault/lib/2015-06-01/generated/azure_key_vault/key_vault_client.rb
data/azure_key_vault/lib/2016-10-01/generated/azure_key_vault/key_vault_client.rb
data/azure_key_vault/lib/7.0-preview/generated/azure_key_vault/key_vault_client.rb
data/azure_key_vault/lib/7.0/generated/azure_key_vault/key_vault_client.rb
data/azure_key_vault/lib/7.1-preview/generated/azure_key_vault/key_vault_client.rb
data/azure_key_vault/lib/7.1/generated/azure_key_vault/key_vault_client.rb
data/azure_key_vault/lib/7.2-preview/generated/azure_key_vault/key_vault_client.rb
data/azure_key_vault/lib/version.rb

closed https://github.com/Azure/azure-sdk-for-ruby/issues/2831

fix key vault issue
