- test/unit/virtual_machine_management/virtual_machine_management_service_test.rb
The dash on the end of the line cause the message match to fail on OS X.
> match slightly less of the error message to work on osx

- .gitignore
Simply add a .ruby-version to the .gitignore to be nice to people using rvm.
> add .ruby-version to .gitignore

- lib/azure/service/serialization.rb
- test/fixtures/storage_service_properties.xml
Seemingly just an optional field that was missed on the serializer.
> Fix: write support for StorageServiceProperties.default_service_version

- lib/azure/virtual_machine_management/virtual_machine_management_service.rb
- test/unit/virtual_machine_management/virtual_machine_management_service_test.rb
Add A10 and A11 to valid role sizes...
But now only warn if a vm is not in the list of valid role sizes and allow Azure to decide whether it is valid or not at runtime.
Fixes #216
> Allow all vm_sizes and warn if an unknown size

- README.md
- lib/azure/core.rb
Change ENV['AZURE_CA_FILE'] to ENV['SSL_CERT_FILE'] so that it's inline with standard env var for cert files.
> default to the openssl environment variable name for ssl_cert_file

- lib/azure/base_management/base_management_service.rb
This replaces "rescue Exception" with "rescue OpenSSL::OpenSSLError" in base_management_service.rb. I also made some minor tweaks so that it uses File.extname instead of a regex, as well as ignoring case, to check for the extension.
https://github.com/Azure/azure-sdk-for-ruby/issues/203
> Don't rescue exception, and use File.extname where appropriate

- lib/azure/core/auth/signer.rb
We discovered this rather ugly error message:
C:/ruby21-x64/lib/ruby/2.1.0/base64.rb:73:in `strict_decode64': undefined method `unpack' for nil:NilClass (NoMethodError)
from C:/ruby21-x64/lib/ruby/gems/2.1.0/gems/azure-0.7.0.pre/lib/azure/core/auth/signer.rb:33:in `initialize'
from C:/ruby21-x64/lib/ruby/gems/2.1.0/gems/azure-0.7.0.pre/lib/azure/core/auth/shared_key.rb:34:in `initialize'
from C:/ruby21-x64/lib/ruby/gems/2.1.0/gems/azure-0.7.0.pre/lib/azure/service/storage_service.rb:25:in `new'
from C:/ruby21-x64/lib/ruby/gems/2.1.0/gems/azure-0.7.0.pre/lib/azure/service/storage_service.rb:25:in `initialize'
from C:/ruby21-x64/lib/ruby/gems/2.1.0/gems/azure-0.7.0.pre/lib/azure/queue/queue_service.rb:23:in `initialize'
This happens if you don't set the storage_access_key in Azure.config …
> Provide sensical error message for invalid storage key

- lib/azure/virtual_machine_management/serialization.rb
Custom images are assigned an image_type of 'VM as compared to stock images, which have a type of 'OS'.
Without adding  || image.image_type == 'VM' at line 92 of serialization.rb, the serialized request does not contain a ConfigurationSet for the OS (only one for the network).
> Missing ConfigurationSet for OS for custom images in request

- lib/azure/base_management/base_management_service.rb
Merged master branch, resolved conflicts :collision: and refactored the file reading code :shower:.
- resolved merge conflicts in base_management_service.rb
- refactored code by moving cert file reading code to a private method named "read_cert_from_file"
> Add support for passing file content directly for management_certificate

- LICENSE.txt
- azure.gemspec
- lib/azure.rb
- lib/azure/base_management/management_http_request.rb
- lib/azure/core/http/http_error.rb
- lib/azure/core/http/http_request.rb
- lib/azure/core/http/http_response.rb
- lib/azure/http_client.rb
- lib/azure/table/serialization.rb
- test/integration/service_bus/queues_scenario_test.rb
- test/integration/service_bus/subscriptions_test.rb
- test/unit/core/auth/shared_key_lite_test.rb
- test/unit/core/http/http_error_test.rb
- test/unit/core/http/http_request_test.rb
- test/unit/core/http/http_response_test.rb
- test/unit/core/http/retry_policy_test.rb
- test/unit/http_client_test.rb
- using faraday rather directly using net/http, which will allow us to get rid of the weird middleware stuff that we are doing in the service.rb and filter_service.rb.
- fixed up corp name and copyright dates in the license.txt
- added a bunch more autoloads
- cleaned up a bunch more of the double quotes
> refactor http framework to use faraday

- test/unit/virtual_machine_management/virtual_machine_management_service_test.rb
This test will fail on a machine with F: for CD/DVD drive.
The reason is the test assumed that when f:/invalid_path/ doesn't exist, the error message is 'No such file or directory ...'. However on a machine with F: as a CD/DVD drive, it doesn't allow to access a path if no CD/DVD is inserted, so the error message will be "... Permission denied...".
Just change to c:/invalid_path, c: will mostly be a system drive and not in such case.
> Make the unit test pass on machines with F: for CD/DVD drive

- README.md
The instructions included strorage twice and the syntax for the Gemfile was incorrect.
> Correct installation instructions for gems

- service_management/azure/lib/azure/blob/blob_service.rb
- service_management/azure/test/integration/blob/block_blob_test.rb
BlobService attempts to synchronize encoding between the Content-Encoding header and the body encoding.  There were two issues:
1) Body can be either a String of IO, but the code only worked with respect to Strings.
2) Azure expects Content-Encoding to be lowercase, otherwise authentication fails.
> Resolves #272 - BlobService::call fails when body is an IO 

- service_management/azure/lib/azure.rb
Azure.vm_disk_management causes error because autoload for VirtualMachineDiskManagementService is missing. This PR fixes this issue. (fixes #269).
> fix VirtualMachineDiskManagementService autoload

- service_management/azure/lib/azure/virtual_machine_management/virtual_machine_management_service.rb
Hello,
I've created an issue in Azure/vagrant-azure project because add_role was not working properly. It appears that this is due to the fact that the add_role method generates on the fly a certificate but does not upload it on Azure.
I've changed this.
Regards,
> fix add_role: make sure that auto_generated certificate is uploaded

- service_management/azure/lib/azure/virtual_machine_management/virtual_machine_management_service.rb
On Virtual Machine deletion there are printed some output directly to STDOUT and that breaks integration with other applications.
This PR fixes this by passing output to Logger like it is done elsewhere.
Fixes #200.
> unify logging on virtual machine deletion

- service_management/azure/lib/azure/blob/blob_service.rb
Azure::Blob::BlobService#create_block_blob raise "RuntimeError: can't modify frozen String" in Ruby 2.3.0 (See. Issue #313 ). This pull request fix.
In Ruby 2.3.0, Encoding#to_s return frozen String.
```ruby
[2] pry(main)> RUBY_VERSION
=> "2.2.4"
[3] pry(main)> "aaa".encoding.to_s.frozen?
=> false
[4] pry(main)> exit
[~]$ rbenv shell 2.3.0
[~]$ pry
[1] pry(main)> RUBY_VERSION
=> "2.3.0"
[2] pry(main)> "aaa".encoding.to_s.frozen?
=> true
[3] pry(main)>
```
> fix raise "can't modify frozen string" exception in Ruby 2.3.0

- service_management/azure/lib/azure/virtual_machine_management/serialization.rb
This enables classic machines to receive custom data as described at
https://msdn.microsoft.com/en-us/library/azure/jj157186.aspx#ConfigurationSets -> CustomData
> Pass custom_data to WindowsProvisioningConfiguration, if available

- README.md
`:partition_key` & `:row_key` do not work with the API.  Additionally, they must be strings to work with the update methods.
> corrects key usage in README

- service_management/azure/lib/azure.rb
- service_management/azure/lib/azure/base_management/management_http_request.rb
- service_management/azure/lib/azure/core/http/http_request.rb
- service_management/azure/lib/azure/http_response_helper.rb
Addressing issue #334 
Adding open_timeout default of 60 seconds, setting it in the Faraday connection. Also correcting setting for read_timeout as Faraday uses timeout.
> adding open_timeout default and correcting setting for read_timeout

- README.md
- service_management/azure/lib/azure/virtual_machine_image_management/virtual_machine_image_management_service.rb
- service_management/azure/lib/azure/virtual_machine_management/virtual_machine_management_service.rb
- service_management/azure/test/integration/vm/VM_Delete_test.rb
the Delete Disk operation does not delete the associated physical VHD file from the blob storage location by default. This PR allow to pass options on the delete_virtual_machine function to delete that VHD.
Ref: #148
> Add delete_virtual_machine options to delete the associated VHD

- service_management/azure/azure.gemspec
- service_management/azure/lib/azure/sql_database_management/sql_database_management_service.rb
1. Updating vcr development dependency from ~>3.0.0 to be ~>3.0
2. Updating SQL Server Database (Classic) REST api endpoint references in docs
> Correct vcr dependency and update SQL Server REST API references

- .travis.yml
Here is the successful azure gem build on private fork and the tag: 
Tag: v0.x.z
Travis File State: [https://github.com/vishrutshah/azure-sdk-for-ruby/blob/v0.x.z/.travis.yml](https://github.com/vishrutshah/azure-sdk-for-ruby/blob/v0.x.z/.travis.yml)
Travis-CI: [https://travis-ci.org/vishrutshah/azure-sdk-for-ruby/builds/124023566](https://travis-ci.org/vishrutshah/azure-sdk-for-ruby/builds/124023566)
> Using only gemspec and branch to master for azure gem deployment

- service_management/azure/lib/azure/virtual_machine_management/serialization.rb
If you see line 22 in serialization.rb, it extends Azure::Core. This file is currently required by external libraries, like fog-azure, on its own. When it's required and azure/core has not been required previously, it'll crash.
> Require azure/core before extending serialization class with it

- Rakefile
- swagger_to_sdk_config.json
This is due to the PR https://github.com/Azure/azure-rest-api-specs/pull/461
> Update Traffic Manager spec location from azure-rest-spi-specs repo

- lib/azure/service_bus/brokered_message_serializer.rb
Work around the error Failed to receive message: 757: unexpected token at '{ "strict-transport-security" : max-age=31536000}', when receiving messages over the Azure Service Bus
@slicke: I've cherry-picked your changes to make a PR into [asm branch](https://github.com/Azure/azure-sdk-for-ruby/tree/asm). Thanks a lot for your contributions. We appreciate your time and efforts. 
Reference PR https://github.com/Azure/azure-sdk-for-ruby/pull/401
Reference Issue https://github.com/Azure/azure-sdk-for-ruby/issues/400
Thanks!
> [ASM] Blacklist strict-transport-security, it crashes the JSON parser when receiving Service Bus messages

- lib/azure.rb
Adding require for azure/core and autoload Auth::SharedAccessSigner, so they don't need to be required from the caller. This needs also a change in azure-core, as azure-core is currently not autoloading auth files, see PR https://github.com/Azure/azure-ruby-asm-core/pull/25.
> Adding require for azure/core and autoload Auth::SharedAccessSigner

- .travis.yml
This reverts commit 13551d6ad045cca1cce956d7e506db8757d8ad97.
Based on the [documentation](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A) when `tag` is `true` then `branch` condition is ignored. Thanks @veronicagg for pointing this out.
> Revert "Use only asm branch to release azure gem (#420)"

- Rakefile
arm:regen was failing due to dir having "management/" in the string, as it was not finding this in REGEN_METADATA at https://github.com/Azure/azure-sdk-for-ruby/blob/master/Rakefile#L59
> Fixing arm:regen in rakefile

- swagger_to_sdk_config.json
Updating swagger to sdk config to fixed version of autorest temporarily, since latest nightly of autorest is broken, and using latest is causing jobs in azure-rest-api-specs repo to fail.
> Updating to fixed version of autorest temporarily

- vcr_helper.rb
#521
Reference: https://www.relishapp.com/vcr/vcr/v/1-7-1/docs/cassettes/request-matching#match-on-host-and-path-(to-ignore-query-params)
With this fix in the recordings pattern matching, we'd not need to re-record recordings in case the query parameters changes (Ex. api_version) in the new swagger.
> Ignore query parameters on recording playback

- .travis.yml
- runtime/ms_rest/lib/ms_rest/http_operation_request.rb
- runtime/ms_rest/lib/ms_rest/service_client.rb
- runtime/ms_rest_azure/Gemfile
- runtime/ms_rest_azure/lib/ms_rest_azure/azure_service_client.rb
- runtime/ms_rest_azure/spec/azure_service_client_spec.rb
This is part of the feature #517. We've exposed `user_agent_extended` array on the [ServiceClient ](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest/lib/ms_rest/service_client.rb#L9) of `ms_rest` to be used for appending additional telemetry information to be sent via `User-Agent` header. 
**User-Agent Header Before** from [AzureServiceClient](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/azure_service_client.rb#L9)
```
Azure-SDK-For-Ruby/0.6.0/
```
**User-Agent Header After** from [AzureServiceClient](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/azure_service_client.rb#L9)
```
Ruby/2.2.4 (x86_64-darwin15) ms_rest/0.6.0 ms_rest_azure/0.6.0 Azure-SDK-For-Ruby
``` …
> Extend user_agent_extended array to add telemetry information

- runtime/ms_rest/lib/ms_rest.rb
- runtime/ms_rest/lib/ms_rest/jsonable.rb
- runtime/ms_rest/lib/ms_rest/serialization.rb
- runtime/ms_rest/spec/jsonable_spec.rb
I found it painful to debug output from the lib since the models don't provide much information when called via to_s. This pull request adds to and from json as well as a more robust to_s implementation which includes the json representation of the model.
> add model to_json, from_json and to_s mixin

- runtime/ms_rest_azure/lib/ms_rest_azure.rb
- runtime/ms_rest_azure/lib/ms_rest_azure/resource.rb
Context for this PR:
In the Swagger Files, there will be a definition for "Resource" and "SubResource" (if they are used). These definitions have historically remained same across the services. 
Resource: name, id, type, location, tags
SubResource: id
Now, there are services such as datalakeanalyticslake, datalakeanalyticsservice, recoveryservicesbackup, etc have added additional properties to them (which is valid). For example, Sku has been added to Resources. 
How are we going to handle it? 
Option 1: We could generate the Resource and SubResource classes per service. This is the approach taken by node sdk. This has been discussed and rejected.
Option 2: We could keep the Resource and SubResource classes as such in the runtime. We could generate the similar classes per service only when …
> Added SubResource/Resource Hierarchy

- management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/edge_nodes.rb
- management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/models/edgenode_result.rb
- management/azure_mgmt_cdn/lib/generated/azure_mgmt_cdn/version.rb
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/922
> Automatic PR from RestAPI-PR922

- Rakefile
- swagger_to_sdk_config.json
@salameer @vishrutshah @veronicagg @amarzavery @daviburg
In this PR, the swagger file used to generate arm_logic has been changed from the compositeswagger to a single file. This has been done for the following reasons:
1. The [composite swagger file](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-logic/CompositeLogicClient.json) is incorrect. It has 2 versions of the same file (with same paths and definitions). 
2. The .NET SDK generation is based on the single file. Refer the script [here](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/generate.cmd). The same applies to Go SDK generation also. Waiting for confirmation from Python & Node SDK teams. 
3. If we do use the compositeswagger files, the …
> Change the swagger file for generating arm_logic sdk

- Rakefile
- swagger_to_sdk_config.json
Change Recovery Services swagger to composite swagger. 
Ref PR; https://github.com/Azure/azure-rest-api-specs/pull/920 
@dsgouda @vishrutshah Please review and approve.
> Change Recovery Services swagger to composite swagger

- azure.gemspec
**Context**
1. 'azure' gem has a dependency on 'nokogiri'. [Dependency Spec: ~>1.6]
2. 'azure' gem must support ruby versions >= 1.9.3 
3. 'nokogiri' has moved to version '1.7' which supports ruby version >= 2.1.0 
**Problem**
Assume a user with ruby version 1.9.3 and using azure gem. While installing the gem, the nokogiri gem version of 1.7 will be attempted to install [since it is compatible to 1.6 - in theory]. But the gem install will fail since nokogiri(1.7) could be installed only on ruby versions >= 2.1.0
**Solution**
We are going to check in the gemspec file for the Ruby version. If the version starts with '1.9'/'2.0' then nokogiri version that is compatible with 1.6.0 could be installed. Else, nokogiri version that is compatible with 1.7 (or greater) could be installed.
**Test** …
> Code changes to handle nokogiri gem version changes

- management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/databases.rb
- management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/models/database_blob_auditing_policy.rb
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1251
> Automatic PR from RestAPI-PR1251

- runtime/ms_rest_azure/lib/ms_rest_azure/azure_service_client.rb
- runtime/ms_rest_azure/lib/ms_rest_azure/polling_state.rb
- runtime/ms_rest_azure/spec/polling_state_spec.rb
Our logic to determine Status in the Polling state object is incorrect. The [Node SDK](https://github.com/Azure/azure-sdk-for-node/blob/0a52678ea7b3a24a478975f7169fc30e9fc9759e/runtime/ms-rest-azure/lib/pollingState.js#L44) and [.NET SDK](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/ClientRuntime.Azure/ClientRuntime.Azure/PollingState.cs#L49) are having similar and correct code. 
This PR is to modify our logic to ensure that it aligns with the logic of .NET and Node SDKs. 
Added rspec tests to ms_rest_azure and confirmed they are passing. Also, pointed ms_rest and ms_rest_azure locally and ran the tests in the entire sdk ruby and confirmed that nothing is breaking.
Please review and approve.
Related to https://github.com/Azure/azure-sdk-for-ruby/issues/817
> Code changes to fix bug related to provisioning status in Polling State Object

- runtime/ms_rest_azure/CHANGELOG.md
- runtime/ms_rest_azure/README.md
- runtime/ms_rest_azure/lib/ms_rest_azure/version.rb
Addresses https://github.com/Azure/azure-sdk-for-ruby/issues/919
> [ms_rest_azure] Preparing to release ms_rest_azure version 0.8.2

- management/azure_mgmt_cognitive_services/lib/generated/azure_mgmt_cognitive_services/check_sku_availability.rb
- management/azure_mgmt_cognitive_services/lib/generated/azure_mgmt_cognitive_services/cognitive_services_management_client.rb
- management/azure_mgmt_cognitive_services/lib/generated/azure_mgmt_cognitive_services/models/cognitive_services_account.rb
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1589
> Automatic PR from RestAPI-PR1589

- runtime/ms_rest_azure/CHANGELOG.md
- runtime/ms_rest_azure/README.md
- runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb
- runtime/ms_rest_azure/lib/ms_rest_azure/version.rb
- runtime/ms_rest_azure/spec/msi_token_provider_spec.rb
> [MsRestAzure] MSI authentication no longer requires use of TenantID in request

- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/action_groups.rb
- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/alert_rules.rb
- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models/action_group_list.rb
- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models/action_group_resource.rb
- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models/activity_log_alert_list.rb
- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models/activity_log_alert_resource.rb
- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models/email_receiver.rb
- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models/service_diagnostic_settings_resource.rb
- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models/service_diagnostic_settings_resource_patch.rb
- management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models/sms_receiver.rb
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1642
> Automatic PR from RestAPI-PR1642

- runtime/ms_rest_azure/CHANGELOG.md
Regarding https://github.com/Azure/azure-sdk-for-ruby/issues/949
> [In Review] Release ms_rest_azure version 0.9.0

- Rakefile
Swallowing errors while publishing to allow publishing of the only new version of the gems
> [rake arm:release] Rescue error while publishing

- Rakefile
This reverts commit 59eeea598daf1868637ef979fab8bef33534d49d.
The reason we added this change was to make sure even one of the gem publish fails we can still try releasing other gems. This was a temporary change but once we have publishing story for individual gem we'll be able to better control how we release an each gem. 
cc: @sarangan12 Let's talk about this in case you were working on release story task :)
> Revert "[rake arm:release] Rescue error while publishing (#972)"

- .travis.yml
CI is failing for PR https://github.com/Azure/azure-sdk-for-ruby/pull/925 for older ruby versions, it appears that travis is running with older versions of bundler. 
Older version is running with 1.8 version and we need fix https://github.com/bundler/bundler/commit/f4481a7e3dbaf7f563e32afbe2cbbb84e3091f16 which was included starting 1.10.
Making bundler version update same as https://github.com/Azure/azure-ruby-asm-core/blob/master/.travis.yml#L8
> Updating bundler version for travis CI

- management/azure_mgmt_network/lib/generated/azure_mgmt_network/models/usage.rb
- management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_interface_load_balancers.rb
- management/azure_mgmt_network/lib/generated/azure_mgmt_network/network_management_client.rb
- management/azure_mgmt_network/lib/generated/azure_mgmt_network/usages.rb
- management/azure_mgmt_network/lib/generated/azure_mgmt_network/virtual_network_gateways.rb
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1640
> Automatic PR from RestAPI-PR1640

- management/azure_mgmt_storage/lib/generated/azure_mgmt_storage.rb
- management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/skus.rb
- management/azure_mgmt_storage/lib/generated/azure_mgmt_storage/storage_management_client.rb
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1650
> Automatic PR from RestAPI-PR1650

- management/azure_mgmt_graph/lib/generated/azure_mgmt_graph/models/application.rb
- management/azure_mgmt_graph/lib/generated/azure_mgmt_graph/models/application_create_parameters.rb
- management/azure_mgmt_graph/lib/generated/azure_mgmt_graph/models/application_update_parameters.rb
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1712
> Automatic PR from RestAPI-PR1712

- management/azure_mgmt_analysis_services/lib/generated/azure_mgmt_analysis_services/servers.rb
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1625
> Automatic PR from RestAPI-PR1625

- config.json
- management/azure_mgmt_links/lib/2016-09-01/generated/azure_mgmt_links.rb
- management/azure_mgmt_links/lib/2016-09-01/generated/azure_mgmt_links/management_link_client.rb
- management/azure_mgmt_links/lib/2016-09-01/generated/azure_mgmt_links/models/resource_link.rb
- management/azure_mgmt_links/lib/2016-09-01/generated/azure_mgmt_links/models/resource_link_filter.rb
- management/azure_mgmt_links/lib/2016-09-01/generated/azure_mgmt_links/models/resource_link_properties.rb
- management/azure_mgmt_links/lib/2016-09-01/generated/azure_mgmt_links/resource_links.rb
Updating config.json to not overwrite title for links package. 
Also re-generating to accompany this change. 
I'll be regenerating all of the other gems with a specific commit hash from rest-api-specs repo and latest autorest, so no need to worry about generation of all for this pr.
> Regen links

- Rakefile
The current clean_generated task deletes the profiles folder (and as a result, the common folder inside the profiles folder). This is not the expected scenario. The Rakefile code has been modified to delete only the multiple API versions folder and not touch the profiles folder.
> Fix for cleaning the multiple versions folders under each sdk

- azure_sdk/lib/v2017_03_09/modules/storage_profile_module.rb
- profile_specs/profiles.json
This is related to [Issue #1117](https://github.com/Azure/azure-sdk-for-ruby/issues/1117). This is a simple change where we need to change the Storage API version from 2015-06-15 to 2016-01-01.
@veronicagg @salameer Please review and approve
> Change Storage API Version in Azure Stack

- runtime/ms_rest_azure/CHANGELOG.md
- runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb
- runtime/ms_rest_azure/lib/ms_rest_azure/version.rb
- runtime/ms_rest_azure/spec/msi_token_provider_spec.rb
Updates to ms_rest_azure to support user assigned identity.
Adding an optional argument to MSITokenProvider creation to support passing user assigned identity, via either client_id, object_id or msi_res_id. 
(similar update for python https://github.com/Azure/msrestazure-for-python/pull/70)
Part of https://github.com/Azure/azure-sdk-for-ruby/issues/1175
> Changes to ms_rest_azure to enable user assigned identity

- swagger_to_sdk_config.json
Updating file pointers for swagger_to_sdk_config.json for the cases where we're pointing to specific files. 
We should probably create tags in the readme files of the below RPs, so those get updated if the repo changes and this update on our side is not needed in the future (we can point to tags in our config file).
Here's a current failing PR https://github.com/Azure/azure-rest-api-specs/pull/2211#issuecomment-355215760
> Swagger to sdk updates due to azure-rest-api-specs repo reorg

- Rakefile
- generators/requirefilegen/src/require_file_generator.rb
- generators/requirefilegen/src/require_file_generator_options_parser.rb
This is related to issue https://github.com/Azure/azure-sdk-for-ruby/issues/1073. 
What does this task do?
1. Parameterize the Rakefile
2. Provided a parameter to regen (such as azure_mgmt_compute) this would regenerate sdk versions and profile for that specific gem and the rollup.
3. If there is no parameter, then the current behavior will continue (that is every gem will be considered)
@veronicagg @salameer Please review and approve
> Rakefile parameterization

- management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/virtual_machine_scale_sets.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3394
> [AutoPR compute/resource-manager] Update VMSS planned maintenance description to refer to best practices doc

- management/azure_mgmt_automation/lib/2015-10-31/generated/azure_mgmt_automation/runbook_draft_operations.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3420
> [AutoPR automation/resource-manager] Changing schema from string to file

- management/azure_mgmt_automation/lib/2015-10-31/generated/azure_mgmt_automation/dsc_configuration_operations.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3749
> [AutoPR automation/resource-manager] Fixing the spec for DSCConfigurations.

- management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/endpoint.rb
- management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/heat_map_model.rb
- management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/profile.rb
- management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/proxy_resource.rb
- management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/resource.rb
- management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/tracked_resource.rb
- management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/traffic_manager_geographic_hierarchy.rb
- management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/user_metrics_model.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4007
> [AutoPR trafficmanager/resource-manager] Do not omit type and name while serializing the resource object.

- azure_sdk/lib/azure_sdk.rb
- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/application.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4348
> [AutoPR graphrbac/data-plane] Fix #4346 - RequiredResourceAccess missing on GET

- management/azure_mgmt_logic/lib/2018-07-01-preview/generated/azure_mgmt_logic/models/key_vault_reference.rb
- management/azure_mgmt_logic/lib/2018-07-01-preview/generated/azure_mgmt_logic/models/resource_reference.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4491
> [AutoPR logic/resource-manager] Microsoft.Logic - Don't make ResourceReference id readonly

- management/azure_mgmt_api_management/lib/2018-01-01/generated/azure_mgmt_api_management/models/backend_service_fabric_cluster_properties.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4510
> [AutoPR apimanagement/resource-manager] typo: Fix apimanagement/resource-manager/Microsoft.ApiManagement/apimbackends.json

- management/azure_mgmt_web/lib/2015-04-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
- management/azure_mgmt_web/lib/2015-04-01/generated/azure_mgmt_web/models/slot_swap_status.rb
- management/azure_mgmt_web/lib/2015-04-01/generated/azure_mgmt_web/models/user.rb
- management/azure_mgmt_web/lib/2015-08-01/generated/azure_mgmt_web/app_service_certificate_orders.rb
- management/azure_mgmt_web/lib/2015-08-01/generated/azure_mgmt_web/models/app_service_certificate_order_collection.rb
- management/azure_mgmt_web/lib/2015-08-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
- management/azure_mgmt_web/lib/2015-08-01/generated/azure_mgmt_web/models/slot_swap_status.rb
- management/azure_mgmt_web/lib/2015-08-01/generated/azure_mgmt_web/models/user.rb
- management/azure_mgmt_web/lib/2016-03-01/generated/azure_mgmt_web/models/csm_usage_quota.rb
- management/azure_mgmt_web/lib/2016-03-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
- management/azure_mgmt_web/lib/2016-03-01/generated/azure_mgmt_web/models/slot_swap_status.rb
- management/azure_mgmt_web/lib/2016-03-01/generated/azure_mgmt_web/models/user.rb
- management/azure_mgmt_web/lib/2016-08-01/generated/azure_mgmt_web/models/csm_usage_quota.rb
- management/azure_mgmt_web/lib/2016-08-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
- management/azure_mgmt_web/lib/2016-08-01/generated/azure_mgmt_web/models/slot_swap_status.rb
- management/azure_mgmt_web/lib/2016-08-01/generated/azure_mgmt_web/models/user.rb
- management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/app_service_environment_patch_resource.rb
- management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/csm_usage_quota.rb
- management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/ramp_up_rule.rb
- management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/slot_swap_status.rb
- management/azure_mgmt_web/lib/2016-09-01/generated/azure_mgmt_web/models/user.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4502
> [AutoPR web/resource-manager] typo: Fix AppServiceCertificateOrders.json

- management/azure_mgmt_cdn/lib/2015-06-01/generated/azure_mgmt_cdn/profiles.rb
- management/azure_mgmt_cdn/lib/2016-04-02/generated/azure_mgmt_cdn/profiles.rb
- management/azure_mgmt_cdn/lib/2016-10-02/generated/azure_mgmt_cdn/models/custom_domain.rb
- management/azure_mgmt_cdn/lib/2016-10-02/generated/azure_mgmt_cdn/models/endpoint.rb
- management/azure_mgmt_cdn/lib/2017-04-02/generated/azure_mgmt_cdn/models/custom_domain.rb
- management/azure_mgmt_cdn/lib/2017-04-02/generated/azure_mgmt_cdn/models/endpoint.rb
- management/azure_mgmt_cdn/lib/2017-10-12/generated/azure_mgmt_cdn/models/cidr_ip_address.rb
- management/azure_mgmt_cdn/lib/2017-10-12/generated/azure_mgmt_cdn/models/custom_domain.rb
- management/azure_mgmt_cdn/lib/2017-10-12/generated/azure_mgmt_cdn/models/endpoint.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4635
> [AutoPR cdn/resource-manager] typo: Microsoft.Cdn

- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/required_resource_access.rb
- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/oauth2.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4693
> [AutoPR graphrbac/data-plane] typo: graphrbac

- management/azure_mgmt_devtestlabs/lib/2016-05-15/generated/azure_mgmt_devtestlabs/models/attach_new_data_disk_options.rb
- management/azure_mgmt_devtestlabs/lib/2016-05-15/generated/azure_mgmt_devtestlabs/models/disk.rb
- management/azure_mgmt_devtestlabs/lib/2016-05-15/generated/azure_mgmt_devtestlabs/models/generate_upload_uri_response.rb
- management/azure_mgmt_devtestlabs/lib/2016-05-15/generated/azure_mgmt_devtestlabs/notification_channels.rb
- management/azure_mgmt_devtestlabs/lib/2018-09-15/generated/azure_mgmt_devtestlabs/models/attach_new_data_disk_options.rb
- management/azure_mgmt_devtestlabs/lib/2018-09-15/generated/azure_mgmt_devtestlabs/models/attach_new_data_disk_options_fragment.rb
- management/azure_mgmt_devtestlabs/lib/2018-09-15/generated/azure_mgmt_devtestlabs/models/disk.rb
- management/azure_mgmt_devtestlabs/lib/2018-09-15/generated/azure_mgmt_devtestlabs/models/disk_fragment.rb
- management/azure_mgmt_devtestlabs/lib/2018-09-15/generated/azure_mgmt_devtestlabs/notification_channels.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4685
> [AutoPR devtestlabs/resource-manager] typo: Microsoft.DevTestLab

- management/azure_mgmt_cognitive_services/lib/2016-02-01-preview/generated/azure_mgmt_cognitive_services/cognitive_services_accounts.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4657
> [AutoPR cognitiveservices/resource-manager] typo: Microsoft.CognitiveServices

- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/alert_properties.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/azure_to_azure_create_network_mapping_input.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/consistency_check_task_details.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/data_store.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/disk_details.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/event_properties.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/in_mage_azure_v2replication_details.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/in_mage_enable_protection_input.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/in_mage_replication_details.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/in_mage_reprotect_input.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/job_query_parameter.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/network_mapping.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/protection_container_fabric_specific_details.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/protection_container_mapping_provider_specific_details.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/resource_health_summary.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/storage_classification.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/storage_classification_mapping.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/update_recovery_plan_input_properties.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/update_vcenter_request_properties.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/vcenter_properties.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/vmm_to_azure_create_network_mapping_input.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/vmm_to_azure_update_network_mapping_input.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/vmm_to_vmm_create_network_mapping_input.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/vmm_to_vmm_update_network_mapping_input.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/models/vmware_virtual_machine_details.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/replication_fabrics.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/replication_jobs.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/replication_storage_classification_mappings.rb
- management/azure_mgmt_recovery_services_site_recovery/lib/2016-08-10/generated/azure_mgmt_recovery_services_site_recovery/replicationv_centers.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4749
> [AutoPR recoveryservicessiterecovery/resource-manager] typo: recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices

- management/azure_mgmt_logic/lib/2018-07-01-preview/generated/azure_mgmt_logic/models/edifact_validation_override.rb
- management/azure_mgmt_logic/lib/2018-07-01-preview/generated/azure_mgmt_logic/models/edifact_validation_settings.rb
- management/azure_mgmt_logic/lib/2018-07-01-preview/generated/azure_mgmt_logic/models/x12validation_override.rb
- management/azure_mgmt_logic/lib/2018-07-01-preview/generated/azure_mgmt_logic/models/x12validation_settings.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4769
> [AutoPR logic/resource-manager] Bugfix for swagger/sdk not matching the underlying service API

- data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/face_list_operations.rb
- data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/large_face_list_operations.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4828
> [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face

- management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/managed_databases.rb
- management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/managed_database.rb
- management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/managed_database_create_mode.rb
- management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/managed_database_status.rb
- management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/managed_database_update.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4907
> [AutoPR sql/resource-manager] Updating managed database swagger

- management/azure_mgmt_recovery_services_backup/lib/2016-12-01/generated/azure_mgmt_recovery_services_backup/models/azure_vm_workload_item.rb
- management/azure_mgmt_recovery_services_backup/lib/2016-12-01/generated/azure_mgmt_recovery_services_backup/models/azure_vm_workload_protectable_item.rb
- management/azure_mgmt_recovery_services_backup/lib/2016-12-01/generated/azure_mgmt_recovery_services_backup/models/azure_workload_recovery_point.rb
- management/azure_mgmt_recovery_services_backup/lib/2016-12-01/generated/azure_mgmt_recovery_services_backup/models/azure_workload_saphana_recovery_point.rb
- management/azure_mgmt_recovery_services_backup/lib/2016-12-01/generated/azure_mgmt_recovery_services_backup/models/azure_workload_sqlrecovery_point.rb
- management/azure_mgmt_recovery_services_backup/lib/2016-12-01/generated/azure_mgmt_recovery_services_backup/models/backup_engine_base.rb
- management/azure_mgmt_recovery_services_backup/lib/2016-12-01/generated/azure_mgmt_recovery_services_backup/models/backup_engine_extended_info.rb
- management/azure_mgmt_recovery_services_backup/lib/2016-12-01/generated/azure_mgmt_recovery_services_backup/models/dpmprotected_item.rb
- management/azure_mgmt_recovery_services_backup/lib/2016-12-01/generated/azure_mgmt_recovery_services_backup/models/key_and_secret_details.rb
- management/azure_mgmt_recovery_services_backup/lib/2017-07-01/generated/azure_mgmt_recovery_services_backup/models/azure_iaa_svmjob_task_details.rb
- management/azure_mgmt_recovery_services_backup/lib/2017-07-01/generated/azure_mgmt_recovery_services_backup/models/dpmprotected_item.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5063
> [AutoPR recoveryservicesbackup/resource-manager] typo: recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices

- management/azure_mgmt_recovery_services_backup/lib/2017-07-01/generated/azure_mgmt_recovery_services_backup/models/backup_status_response.rb
- management/azure_mgmt_recovery_services_backup/lib/2017-07-01/generated/azure_mgmt_recovery_services_backup/models/pre_validate_enable_backup_request.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5133
> [AutoPR recoveryservicesbackup/resource-manager] Fixing a minor bug in Recovery Services (Backup) 

- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/application.rb
- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/application_base.rb
- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/optional_claim.rb
- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/service_principal.rb
- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/service_principal_base.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5375
> [AutoPR graphrbac/data-plane] typo: graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6

- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/application_create_parameters.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5425
> [AutoPR graphrbac/data-plane] graph: identifierUris should not be required

- management/azure_mgmt_network/lib/2018-12-01/generated/azure_mgmt_network/ddos_protection_plans.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5426
> [AutoPR network/resource-manager] Patch call for DDoS Protection plan

- data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/large_face_list_operations.rb
- data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/large_person_group_operations.rb
- data/azure_cognitiveservices_face/lib/1.0/generated/azure_cognitiveservices_face/person_group_operations.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5482
> [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face/stable/v1

- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/service_principal.rb
- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/service_principal_base.rb
- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/service_principal_create_parameters.rb
- data/azure_graph_rbac/lib/1.6/generated/azure_graph_rbac/models/service_principal_update_parameters.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5873
> [AutoPR graphrbac/data-plane] graph: fix invalid types of accountEnabled

- management/azure_mgmt_event_hub/lib/2015-08-01/generated/azure_mgmt_event_hub/event_hubs.rb
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6407
> [AutoPR eventhub/resource-manager] Eventhub: fixed typo in 2015 API version swagger

- runtime/ms_rest/lib/ms_rest/version.rb
ms_rest 0.7.4 -> 0.7.5
The real changes were already contained in another PR: #2733 
Release process: 
1. Bump the version in the `runtime/ms_rest/lib/ms_rest/version.rb`;
2. Run command `rake build` and `rake release` under path `runtime/ms_rest`;
3. Check https://rubygems.org/gems/ms_rest .
> Release ms_rest 0.7.5

- README.md
The link to the Azure deployment models documentation is broken as it has a spurious `` ` `` at the end. This PR removes this character so the link works.
> Fix link to Azure development models reference
